### ISSUE TITLE
tsapp should support meta data from .tid files

### ISSUE THREAD

**Issue by pads** [cdent/tsapp#10]
For example, when pushing a .tid file to a space it should include meta data such as tags.

It should also be able to serve these files but this does mean serialisation needs to occur.  

A rather simplistic approach to being with (if inelegant) could be to just support HTML files and ignore the meta data when serving the file.

**Comment by cdent** [comment]
The push situation is relatively easy to handle: we can push a `*.tid` as `text/plain` and server side the text serialization will deal with whatever metadata is in the header of the tid.

When operating `tsapp` as a proxy, the situation is more difficult:
- currently tsapp won't see the .tid file by its non-extension name
- if it could, it wouldn't know how to process the headers

(similar issues apply to `*.meta` files, which can also be associated with files to add metadata)

Both of these things can be changed, but it's hard to know what the best approach is. Early on a design goal of `tsapp` was to not have any dependencies. If we give up that constraint we can use code from `tiddlywebplugins.twimport` and `tiddlyweb` to process the files. If we don't want to give up that constraint there are relatively short tricks we can use to process the data.

Some input from @colmjude (as a regular user of tsapp) and @FND (as a guy who has opinions) would be useful.

**Comment by cdent** [comment]
Note that my solution the general problem of wanting to have assets with metadata is to just put those assets on the server. tsapp only really works when it can be talking to the server, so the point is not to replace the server, rather to augment it with a system which allows those files you want to edit locally (html, css, javascript) to be easy to edit.

I'm not denying there might need to be a solution here, but suggesting that what we need, in this ticket, is a description of the problem not the solution.

**Comment by cdent** [comment]
I think we've figured out we don't need this.
