### ISSUE TITLE
Tank API Keys

### ISSUE THREAD

**Issue by edrex** [cdent/tsapp#15]
Tank doesn't do password auth (thank you!) so I created a Tank API key through the UI and added it to `.tsapp` so it looks like:

```
auth_token:eric:<my api key>
tiddlyweb_mode:true
target_server:https://tank.peermore.com
```

but I'm getting `403 Forbidden`.

**Comment by edrex** [comment]
Just read https://tank.peermore.com/tanks/docs/API and realized it's a different header (`X-Tank-Key: <key>` vs `Cookie: tiddlyweb_user=someuser:<key>` for [standard tiddlyweb](http://tiddlyweb.tiddlyspace.com/Authenticating%20with%20curl)).

**Comment by edrex** [comment]
meh, this is probably out of scope for tsapp. Anyway there are plenty of good REST tools (and a few TiddlyWeb-oriented ones as well)

**Comment by cdent** [comment]
Once you have a browser logged into tank (after doing the oauth dance) you'll have a tiddlyweb_user cookie that you can steal in the same way as done when using tsapp with tiddlyspace. That ought to get auth working.

I suspect, however, that there might be some other weirdnesses once you are past that hurdle. However it is all just bags and recipes under the hood so in tiddlyweb_mode it will at least be close. If you choose to try it and get it working with some adjustments please feel free to provide a pull request. There's no reason tsapp should be just ts...
